name: Check if License-3rdparty is up to date on PR

on: [pull_request, push]
permissions:
  contents: read

jobs:
  license-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: 'go.mod'
          check-latest: true
      - name: Installing modvendor tool
        run: go install github.com/goware/modvendor@latest
      - name: Installing wwhrd tool
        run: go install github.com/frapposelli/wwhrd@latest
      - name: Installing go-license-detector tool
        run: GO111MODULE=on go install github.com/go-enry/go-license-detector/v4/cmd/license-detector@latest
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.9.12"
          cache: "pip"
      - name: Install dependencies
        run: python3 -m pip install -r .github/scripts/lint-licenses/requirements.txt
      - name: Run license lint task
        run: inv -r .github/scripts/lint-licenses -e lint-licenses

